[package]
name = "atari800-rs"
version = "0.1.0"
authors = ["mypalmike"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.0"
sdl2 = "0.35"
